# Generated by Django 5.0.3 on 2024-03-28 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido_Paterno', models.CharField(max_length=255)),
                ('Apellido_Materno', models.CharField(blank=True, max_length=255, null=True)),
                ('Correo', models.EmailField(max_length=255, unique=True)),
                ('NumeroCelular', models.CharField(blank=True, max_length=20, null=True)),
                ('Rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ultrasonidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_files', models.TextField()),
                ('TipoDeUltrasonidos', models.CharField(max_length=255)),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnlaceDigna.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnlaceDigna.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnlaceDigna.usuarios'),
        ),
    ]
