# Generated by Django 5.0.3 on 2024-03-25 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido_Paterno', models.CharField(max_length=255)),
                ('Apellido_Materno', models.CharField(blank=True, max_length=255, null=True)),
                ('Correo', models.EmailField(max_length=255, unique=True)),
                ('NumeroCelular', models.CharField(blank=True, max_length=20, null=True)),
                ('Rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ultrasonido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_files', models.CharField(max_length=255)),
                ('TipoDeUltrasonidos', models.CharField(max_length=255)),
                ('Fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnlaceDigna.cliente')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnlaceDigna.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnlaceDigna.usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnlaceDigna.usuario'),
        ),
    ]
