# Generated by Django 5.0.3 on 2024-03-22 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=70)),
                ('numero_telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Ultrasonidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_files', models.CharField(max_length=100)),
                ('tipo_ultrasonido', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnlaceDigna.usuarios')),
            ],
        ),
    ]
