# Generated by Django 5.0.3 on 2024-03-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
