# Generated by Django 5.0.3 on 2024-03-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultrasonido',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='ultrasonido',
            name='Fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='EnlaceDigna_cliente',
        ),
    ]
