# Generated by Django 5.0.3 on 2024-04-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0002_doctor_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(default='pbkdf2_sha256$720000$vB44UBzmOhLZ7KLzARtLSd$ZakXntS8hR8o0ifCEc74BBahl1+8NydtSS7FKzU66P0=', max_length=128),
        ),
    ]
