# Generated by Django 5.0.3 on 2024-04-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0002_doctor_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(default='pbkdf2_sha256$720000$AzgwXCKNvwzYxp1SZl1Tvv$JR9LSz+uorpzJgfpcZE/1zzyjSEUvCUsePGY9FrFALM=', max_length=128),
        ),
    ]
