# Generated by Django 5.0.3 on 2024-03-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0002_remove_ultrasonido_doctor_alter_ultrasonido_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
    ]
