# Generated by Django 5.0.3 on 2024-04-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0003_usuarios_last_login_alter_doctor_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(default='pbkdf2_sha256$720000$tqH3AF02dyVWL88ty1jIP9$x4sOtYzrflTH6/Xn0A1jMJsrxYq6oF8+/mv2DbDMw+8=', max_length=128),
        ),
    ]
