# Generated by Django 5.0.3 on 2024-03-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0003_alter_cliente_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultrasonido',
            name='ruta_files',
            field=models.TextField(),
        ),
    ]
