# Generated by Django 5.0.3 on 2024-04-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0003_alter_doctor_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(default='pbkdf2_sha256$720000$L06oG6PWRTw4NQ09jYhN5M$bZl479MJaNcSU1RSkp57MhrzILxkFYFuN+zU+C73EZI=', max_length=128),
        ),
    ]
