# Generated by Django 5.0.3 on 2024-04-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0005_alter_doctor_contraseña_alter_ultrasonidos_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(default='pbkdf2_sha256$720000$NolKl3BCNweCgHQQbaAySm$p5KaHbLWNnwpbft7KiRy9OuJ4e687isFGQyCVk36878=', max_length=128),
        ),
    ]
