# Generated by Django 5.0.3 on 2024-04-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0007_remove_cliente_token_ultrasonidos_tokenultrasonido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(default='pbkdf2_sha256$720000$797gMyZAmIB9usbmLRmCeE$6iTlonRcGE80BFoHFo2mwJVCxPHnKwIlY9QUzpqYGjU=', max_length=128),
        ),
    ]
