# Generated by Django 5.0.3 on 2024-04-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0008_alter_doctor_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(default='pbkdf2_sha256$720000$nfxy5TEdqih3SMAf7ikzJ1$z7aj98zsukgGzqPaBEC3RIoqCNkh8NhX7Ue6frzR4BU=', max_length=128),
        ),
    ]
