# Generated by Django 5.0.3 on 2024-04-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0009_alter_doctor_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(default='pbkdf2_sha256$720000$eNrQ2rrGoDVDBUXve1C0eg$f/WVmLZUbXzpqboPOBJU7xrZDyWFYfdjnEfKtIbHY9E=', max_length=128),
        ),
    ]
