# Generated by Django 5.0.3 on 2024-04-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0010_remove_usuarios_is_authenticated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('opcion_seleccionada', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(default='pbkdf2_sha256$720000$YFDXu7Tfrkk34JGnPc82nS$cXlRSDl1CDqU0wRdAmvdoG4HjLNynmnVuHnzbeO4NHI=', max_length=128),
        ),
    ]
