# Generated by Django 5.0.3 on 2024-04-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0010_remove_usuarios_is_authenticated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(default='pbkdf2_sha256$720000$791ZGStCfarKgox26mYKAF$WY8e83A/ucE9eojP9K5+4B8lNXVrr7f36+Rz20tGijM=', max_length=128),
        ),
    ]
