# Generated by Django 5.0.3 on 2024-04-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0011_alter_doctor_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(default='pbkdf2_sha256$720000$ksPLvGH7IwtSATYwQo9f8p$lcafQO+pVj/m/X9HUGeUgxWg1Q5JTYo1PQ6qISN4SjQ=', max_length=128),
        ),
    ]
