# Generated by Django 5.0.3 on 2024-04-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0011_estadousuario_alter_doctor_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasonidos',
            name='OpcionUltra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(default='pbkdf2_sha256$720000$Zrr1go5PvXXxG4stZ0Qajz$hMHb0cIAuVLL6sRsoIgz1W5C2n6QSb8CqdSLq+a3hNo=', max_length=128),
        ),
    ]
