# Generated by Django 5.0.3 on 2024-04-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnlaceDigna', '0012_alter_doctor_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(default='pbkdf2_sha256$720000$dh4KD8E4IcxvgEwxDqHFot$GznQLOE8GSYoNJXAI9rwCEqr3lmdWEz64D7Lwd03QZw=', max_length=128),
        ),
    ]
